import { memo, useEffect, useState, type MouseEvent } from "react";
import { AnimatePresence } from "framer-motion";

import classes from "./GeneratedImages.module.scss";
import Modal from "../../ui/Modal";
import SaveImageForm from "../../forms/save-image-form/SaveImageForm";
import Button from "../../ui/buttons/Button";
import ErrorMessage from "../../ui/ErrorMessage";
import { useOnlineStatus } from "../../../hooks/use-online-status";
import {
  GUIDE_STEP_GENERATED_IMAGES,
  ERROR_MESSAGE_OFFLINE,
} from "../../../variables/constants";
import GeneratedImagesGuide from "../../general-elements/guide/model/GeneratedImagesGuide";
import SavedImages from "./saved-images/SavedImages";
import ExternalImages from "./external-images/ExternalImages";
import ButtonInfo from "../../ui/buttons/ButtonInfo";
import InfoGeneratedImages from "../../general-elements/info/InfoGeneratedImages";
import ModelVersionsList from "../model-versions-list/ModelVersionsList";
import ImageTabs from "./image-tabs/ImageTabs";
import { useAppSelector } from "../../../store/hooks/hooks";
import Tooltip from "../../ui/Tooltip";
import ModelTooltip from "../model-tooltip/ModelTooltip";

const imageSortValue = "Newest";
/**
 * Displays images generated by the active model with infinite scroll support.
 *
 * Responsibilities:
 * - Displays generated and saved images for the selected model.
 * - Allows switching between model versions and image scopes (saved / all).
 * - Provides actions to add images manually and access contextual hints.
 *
 * Additional features:
 * - Infinite scrolling for large image sets.
 * - Popup flow for adding images by post ID.
 *
 * @component
 *
 * @returns {JSX.Element} Generated images component.
 */
const GeneratedImages = memo(() => {
  const [curTab, setCurTab] = useState("all");
  const [curVersionId, setCurVersionId] = useState<number | null>(null);
  const [addImgModalIsOpen, setAddImgModalIsOpen] = useState(false);
  const curVersion = useAppSelector((state) => state.model.curVersion);
  const model = useAppSelector((state) => state.model.model);
  const savedImagesData = useAppSelector((state) => state.model.savedImages);
  const savedImages =
    model?.id && model.id === savedImagesData?.modelId
      ? savedImagesData.data
      : null;
  const guideIsActive = useAppSelector((state) => state.guide.active);
  const guideStep = useAppSelector((state) => state.guide.model.step);
  const isOnline = useOnlineStatus();

  let versionsCustomData =
    model?.modelVersionsCustomData &&
    Object.values(model?.modelVersionsCustomData)?.sort((a, b) => {
      if (a?.index !== undefined && b?.index !== undefined) {
        return a.index - b.index;
      }
      return 0;
    });

  if (curTab === "saved") {
    versionsCustomData = versionsCustomData?.filter((version) => {
      const isSaved =
        savedImages &&
        Object.keys(savedImages).includes(`${version.versionId}`);
      return curTab === "saved" && isSaved;
    });
  }

  useEffect(() => {
    if (curVersion?.id) setCurVersionId(curVersion.id);
  }, [curVersion]);

  const openVersionHandler = (e: MouseEvent<HTMLElement>) => {
    if (!(e.target instanceof HTMLElement)) return;
    if (+e.target.id === curVersionId) return;

    setCurVersionId(+e.target.id);
  };

  const switchCurTab = (tab: string) => {
    if (curTab === tab) return;
    setCurTab(tab);
    if (
      tab !== "all" &&
      savedImages &&
      curVersionId &&
      !Object.hasOwn(savedImages, curVersionId)
    ) {
      const latesVersionId =
        model &&
        model.modelVersionsCustomData &&
        Object.values(model.modelVersionsCustomData)
          .sort((a, b) => {
            if (a?.index !== undefined && b?.index !== undefined) {
              return a.index - b.index;
            }
            return 0;
          })
          .find((version) => Object.hasOwn(savedImages, version.versionId))
          ?.versionId;
      if (latesVersionId) {
        setCurVersionId(latesVersionId);
      }
    }
  };

  const addImgByIdHandler = () => {
    setAddImgModalIsOpen(true);
  };

  return (
    <div className={classes.container}>
      <div className={classes["controls"]}>
        <ImageTabs
          curTab={curTab}
          onClick={switchCurTab}
          saved={!!model?.modelVersionsCustomData}
        />
        <Button
          className={classes["button-add"]}
          onClick={addImgByIdHandler}
          disabled={!model?.modelVersionsCustomData}
        >
          <Tooltip
            className={classes["tags__btn-edit-tooltip"]}
            content={!model?.modelVersionsCustomData ? <ModelTooltip /> : ""}
          >
            Add Image by ID
          </Tooltip>
        </Button>
        <ButtonInfo>
          <InfoGeneratedImages />
        </ButtonInfo>
      </div>
      <ModelVersionsList
        onClick={openVersionHandler}
        itemComponent="span"
        versionsCustomData={versionsCustomData}
        curVersionId={curVersionId}
        modelVersions={model?.data?.modelVersions}
      />
      <div
        className={`${classes["images-container"]} ${
          guideIsActive && guideStep === GUIDE_STEP_GENERATED_IMAGES
            ? classes["images-container--guide"]
            : ""
        }`}
      >
        <GeneratedImagesGuide />
        <div className={classes.images}>
          {curTab === "all" && model && curVersionId && (
            <ExternalImages
              modelId={model.id}
              versionId={curVersionId}
              sortBy={imageSortValue}
              modelIsSaved={!!model.modelVersionsCustomData}
            />
          )}
          {curTab === "saved" && curVersionId && (
            <SavedImages versionId={curVersionId} />
          )}
        </div>
      </div>
      {!isOnline && <ErrorMessage>{ERROR_MESSAGE_OFFLINE}</ErrorMessage>}
      <AnimatePresence>
        {addImgModalIsOpen && (
          <Modal
            title="Add images by Post ID"
            onClose={() => {
              setAddImgModalIsOpen(false);
            }}
          >
            <SaveImageForm
              modelData={model}
              curVersion={curVersionId}
              location="models"
              savedModelPosts={savedImagesData?.data}
            />
          </Modal>
        )}
      </AnimatePresence>
    </div>
  );
});

export default GeneratedImages;
