export const DEV_GUIDE_TEST = false;

//GUIDE STEPS HOME PAGE
export const GUIDE_STEP_OPEN_CATEGORY = 1;
export const GUIDE_STEP_OPEN_MODEL = 2;

//GUIDE STEPS MODEL PAGE
export const GUIDE_STEP_ADD_MODEL_TO_SIDEPANEL = 1;
export const GUIDE_STEP_ADD_IMAGE_TO_SIDEPANEL = 2;
export const GUIDE_STEP_SIDEPANEL = 3;
export const GUIDE_STEP_SIDEPANEL_VIEW_SWITCH = 4;
export const GUIDE_STEP_OPEN_IMAGE = 5;
export const GUIDE_STEP_ADD_TO_PROMPT = 6;
export const GUIDE_STEP_ADD_ALL_TO_PROMPT = 7;
export const GUIDE_STEP_SWITCH_IMAGE = 8;
export const GUIDE_STEP_HIGHLIGHTING_WORDS = 9;
export const GUIDE_STEP_PROMPT_VIEW = 10;
export const GUIDE_STEP_PROMPT_PRESETS = 11;
export const GUIDE_STEP_PROMPT_BREAK = 12;
export const GUIDE_STEP_PROMPT_DRAG_AND_DROP = 13;
export const GUIDE_STEP_PROMPT_EDIT_TAG = 14;
export const GUIDE_STEP_PROMPT_RESIZE = 15;
export const GUIDE_STEP_PROMPT_COPY = 16;
export const GUIDE_STEP_IMAGE_RESOURCES = 17;
export const GUIDE_STEP_CLOSE_IMAGE = 18;
export const GUIDE_STEP_MODEL_TAGS_EDIT = 19;
export const GUIDE_STEP_MODEL_TAGS_EDIT_FROM = null;
export const GUIDE_STEP_MODEL_TAGS_ADD_TAGSET = null;
export const GUIDE_STEP_MODEL_TAGS_CLOSE = null;
export const GUIDE_STEP_MODEL_ADD_TAGSET = 20;
export const GUIDE_STEP_MODEL_TAGSET = 21;
export const GUIDE_STEP_GENERATED_IMAGES = 22;
export const GUIDE_STEP_IMAGE_MENU = 23;
export const GUIDE_STEP_SAVE_IMAGE = 24;
export const GUIDE_STEP_SAVED_TAB = 25;
export const GUIDE_STEP_MODEL_EDIT = 26;

//GUIDE STEPS EDIT PAGE
export const GUIDE_STEP_EDIT_UPD_DEL = 1;
export const GUIDE_STEP_EDIT_VERSIONS_SWITCH = 2;
export const GUIDE_STEP_EDIT_DEFAULT = 3;
export const GUIDE_STEP_EDIT_MENU = 4;

//GUIDE
export const GUIDE_LAST_STEP_TYPE = "edit";
export const GUIDE_LAST_STEP = GUIDE_STEP_EDIT_MENU;
