//VALIDATION
export const VALIDATION_CATEGORY_NAME_MAX_LENGTH = 70;
export const VALIDATION_USERNAME_MAX_LENGTH = 100;
export const VALIDATION_NAME_MAX_LENGTH = 300;
export const VALIDATION_TITLE_MAX_LENGTH = 500;
export const VALIDATION_DESCRIPTION_MAX_LENGTH = 100000;
export const VALIDATION_TRIGGER_WORDS_MAX_LENGTH = 5000;
export const VALIDATION_POST_URL_MAX_LENGTH = 45;
export const VALIDATION_NUMBER_MAX_LENGTH = 5;
export const VALIDATION_EMAIL_MAX_LENGTH = 50;
export const VALIDATION_PASSWORD_MAX_LENGTH = 100;
export const VALIDATION_PASSWORD_MIN_LENGTH = 6;
export const VALIDATION_PASSWORD_SPECIAL_CHARACTERS = /!|@|#|\$|%/;
export const VALIDATION_VALIDATE_PASSWORD_SPECIAL_CHARACTERS = false;
export const VALIDATION_VALIDATE_PASSWORD_LETTER_COMBINATION = true;
export const VALIDATION_VALIDATE_PASSWORD_NUMBER_INCLUSION = false;
