import {
  CheckCircleIcon,
  Cog6ToothIcon,
  ExclamationCircleIcon,
  FolderArrowDownIcon,
  PencilSquareIcon,
  PlusIcon,
} from "@heroicons/react/24/outline";
import Image from "../ui/image/Image";
import TextButton from "../ui/text/text-buttons/TextButton";
import TextHighlight from "../ui/text/TextHighlight";
import classes from "./AboutModelPage.module.scss";
import Text from "../ui/text/Text";
import TextImageBlock from "../ui/text/TextImageBlock";
import TextContentBlock from "../ui/text/TextContentBlock";
import TextButtonTertiary from "../ui/text/text-buttons/TextButtonTertiary";
import TextButtonAll from "../ui/text/text-buttons/TextButtonAll";
import H3 from "../ui/text/H3";
import TextImageMenu from "../ui/text/text-buttons/TextImageMenu";
import NotificationMessage from "../ui/NotificationMessage";
import TextButtonSquare from "../ui/text/text-buttons/TextButtonSquare";
import TextButtonSaved from "../ui/text/text-buttons/TextButtonSaved";
import AboutAddImageById from "./AboutAddImageById";
import AboutTagSets from "./AboutTagSets";
import AboutContentWrap from "./layout/AboutContentWrap";
import H1 from "../ui/text/H1";
import { Link } from "react-router-dom";
import AboutSection from "./layout/AboutSection";

const AboutModelPage = () => {
  return (
    <AboutContentWrap>
      {" "}
      <H1 id="model">Model Page</H1>
      <TextContentBlock>
        <Text>
          Under model's name, there are tabs for model versions. The names of
          versions marked as downloaded in the settings are purple, and those
          not downloaded are white.
        </Text>
        <TextImageBlock>
          <Image
            loading="lazy"
            width={1909}
            height={918}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/13-model-page-1.jpg")}
            alt="Model page 1"
            srcSet={require("../../assets/about/13-model-page-1.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <Text>
          Below the model images, there is an information block about the model.
          There will be displayed data you entered in the Settings, as well as a
          block with trigger words where you can see all the added tags.
        </Text>
        <TextImageBlock>
          <Image
            loading="lazy"
            width={1909}
            height={918}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/13-model-page-2.jpg")}
            alt="Model page 2"
            srcSet={require("../../assets/about/13-model-page-2.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <Text>
          Clicking on a tag will add it to the prompt, and clicking again on an
          already added tag will remove it from the prompt. If some tags are
          already in the prompt, they will be{" "}
          <TextButtonTertiary className={classes.tag}>
            highlighted
          </TextButtonTertiary>
          . With the <TextButtonAll>Add All</TextButtonAll> and{" "}
          <TextButtonAll>Remove All</TextButtonAll> buttons, you can add or
          remove the entire group of tags from the prompt. When removing a
          group, the rest of the prompt will remain unchanged.
        </Text>
        <Text>
          The{" "}
          <TextHighlight>
            "Edit... <PencilSquareIcon className={classes["svg"]} />"
          </TextHighlight>{" "}
          button in the top right corner of the block gives you quick access to
          editing trigger words of the current version.
        </Text>
        <TextImageBlock col={2}>
          <Image
            loading="lazy"
            width={1909}
            height={918}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/22-edit-btn-model-1.jpg")}
            alt="Edit button model 1"
            srcSet={require("../../assets/about/22-edit-btn-model-1.webp")}
            type="image/webp"
          />
          <Image
            loading="lazy"
            width={1909}
            height={918}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/22-edit-btn-model.jpg")}
            alt="Edit button model 2"
            srcSet={require("../../assets/about/22-edit-btn-model.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <AboutTagSets />
        <AboutSection id="images">
          <H3>Generated Images</H3>
          <Text>
            On the model page, after the basic information and description, you
            will find images generated by users with this model. You can{" "}
            <TextHighlight>save images</TextHighlight> from the generated list
            either <TextHighlight>to the current model page</TextHighlight> or{" "}
            <Link
              className={classes.link}
              to={{
                pathname: `/about/image-collections`,
                hash: "collection",
              }}
            >
              to a separate collection
            </Link>
            , so you can use them as references later.
          </Text>
          <Text>
            To save image to the current model page use the{" "}
            <TextButtonSquare>
              <FolderArrowDownIcon />
            </TextButtonSquare>{" "}
            <TextHighlight>"Save to Model"</TextHighlight> button at the top
            left of an image. If there is more than one image, a popup window
            will open where you can select the images you want to save. Click{" "}
            <TextButton>Save All</TextButton> or{" "}
            <TextButton>Save Selected</TextButton> to add it to the{" "}
            <TextButtonSaved /> tab of the current model.
          </Text>
          <TextImageBlock col={2}>
            <Image
              loading="lazy"
              width={1909}
              height={918}
              fullView={true}
              className={classes["img"]}
              src={require("../../assets/about/14-img-examples-1.jpg")}
              alt="Image examples 1"
              srcSet={require("../../assets/about/14-img-examples-1.webp")}
              type="image/webp"
            />
            <Image
              loading="lazy"
              width={1909}
              height={918}
              fullView={true}
              className={classes["img"]}
              src={require("../../assets/about/14-img-examples-2.jpg")}
              alt="Image examples 2"
              srcSet={require("../../assets/about/14-img-examples-2.webp")}
              type="image/webp"
            />
          </TextImageBlock>
        </AboutSection>
        <H3 id="addbyid">Add image by post ID</H3>
        <Text>
          Use the <TextButton>Add image by ID</TextButton> button to save an
          image by the post ID from Civitai. To add an image, use the{" "}
          <TextHighlight>Post ID</TextHighlight> from Civitai (not the image
          ID).{" "}
        </Text>
        <AboutAddImageById />
        {/* <InfoPostId /> */}
        <Text>
          Return to the site and enter the post ID, select the model version,
          and select the images that you want to save.
        </Text>
        <TextImageBlock col={2}>
          <Image
            loading="lazy"
            width={1409}
            height={797}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-5.jpg")}
            alt="Image examples 3"
            srcSet={require("../../assets/about/14-img-examples-5.webp")}
            type="image/webp"
          />
          <Image
            loading="lazy"
            width={1409}
            height={797}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-52.jpg")}
            alt="Image examples 4"
            srcSet={require("../../assets/about/14-img-examples-52.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <NotificationMessage
          type="notification"
          className={classes.notification}
        >
          <Text>
            Saved images are not stored on the server; only generation data is
            stored. If an image is removed from the Civitai site, it will become
            unavailable, but the generation data will be preserved and available
            for use.
          </Text>
        </NotificationMessage>
        <Text>
          In the <TextButtonSaved /> tab, the image menu <TextImageMenu />{" "}
          includes an option to delete images. You can delete either selected
          images or all of them at once.
        </Text>
        <TextImageBlock col={2}>
          <Image
            loading="lazy"
            width={1491}
            height={754}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-3.jpg")}
            alt="Image examples 3"
            srcSet={require("../../assets/about/14-img-examples-3.webp")}
            type="image/webp"
          />
          <Image
            loading="lazy"
            width={1491}
            height={754}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-4.jpg")}
            alt="Image examples 4"
            srcSet={require("../../assets/about/14-img-examples-4.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <Text>
          With the{" "}
          <TextButtonSquare>
            <PlusIcon />
          </TextButtonSquare>{" "}
          button, any image can be added to the sidebar as a reference. Clicking
          the button again will remove the image from the sidebar.
        </Text>
        <TextImageBlock>
          <Image
            loading="lazy"
            width={1491}
            height={754}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-6.jpg")}
            alt="Image examples 5"
            srcSet={require("../../assets/about/14-img-examples-6.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <Text>
          Any image on the model page can be set as the model preview. To do
          this, in the image menu <TextImageMenu /> select{" "}
          <TextHighlight>"Set as Preview"</TextHighlight>. If the NSFW mode is
          enabled in the Top Bar, the menu will also include the option{" "}
          <TextHighlight>"Set as NSFW Preview"</TextHighlight>. Each model can
          have two previews: one for SFW and one for NSFW mode.
        </Text>
        <TextImageBlock col={2}>
          <Image
            loading="lazy"
            width={1491}
            height={754}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-7.jpg")}
            alt="Image examples 6"
            srcSet={require("../../assets/about/14-img-examples-7.webp")}
            type="image/webp"
          />
          <Image
            loading="lazy"
            width={1491}
            height={754}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-8.jpg")}
            alt="Image examples 7"
            srcSet={require("../../assets/about/14-img-examples-8.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <NotificationMessage
          type="notification"
          className={classes["notification"]}
        >
          You cannot upload your own image directly to the site. However, you
          can upload it to Civitai under the corresponding model as a generation
          example or simply as a separate post, and then add it to saved images
          using the <TextButton>Add Image by ID</TextButton> button. After this,
          you can use the image as a model preview or tag sets.
        </NotificationMessage>
        <Text>
          When you click on an image, a popup window will appear where you can
          see its prompt, add necessary tags, and view generation data.
        </Text>
        <TextImageBlock>
          <Image
            loading="lazy"
            width={1491}
            height={754}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-9.jpg")}
            alt="Image examples 8"
            srcSet={require("../../assets/about/14-img-examples-9.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <Text>
          There you will also find resources used during generation: models,
          their versions, type, weight, and source.
        </Text>
        <TextImageBlock>
          <Image
            loading="lazy"
            width={1909}
            height={918}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-resources3.jpg")}
            alt="Image examples resources"
            srcSet={require("../../assets/about/14-img-examples-resources3.webp")}
            type="image/webp"
          />
        </TextImageBlock>
        <Text>
          <TextButtonSquare>
            <FolderArrowDownIcon className={classes.svg} />
          </TextButtonSquare>{" "}
          – Click to save the current resource to your collection. If the
          resource is already downloaded, the button will be replaced with a{" "}
          <TextButtonSquare>
            <PlusIcon className={classes.svg} />
          </TextButtonSquare>
          , which you can use to add the resource to the sidebar.
        </Text>
        <Text>
          <TextButtonSquare>
            <PlusIcon className={classes.svg} />
          </TextButtonSquare>{" "}
          – Click to add the model to the sidebar for quick access. Clicking
          again will remove the model from the sidebar.
        </Text>
        <Text>
          If the model is already in your collection, its name will appear as a{" "}
          <span className={classes.link}>blue link</span> — click it to navigate
          to the model’s page.
        </Text>
        <H3>Version tracking</H3>
        <Text>
          If the resource is downloaded, you’ll see two indicators to help track
          its versions.
        </Text>
        <Text>
          You can mark versions as downloaded or not downloaded in the{" "}
          <Link
            className={classes.link}
            to={{
              pathname: `/about/model-settings`,
              hash: "settings",
            }}
          >
            model settings
          </Link>{" "}
          by clicking the{" "}
          <TextButton>
            <Cog6ToothIcon /> Edit
          </TextButton>{" "}
          button on the model page.
        </Text>
        <Text>
          <CheckCircleIcon
            className={`${classes["status"]} ${classes["status--saved"]}`}
          />{" "}
          - Indicates that the version used as a resource is{" "}
          <TextHighlight>marked</TextHighlight> as downloaded.
        </Text>
        <Text>
          <ExclamationCircleIcon className={classes["status"]} /> - Indicates
          that the version used as a resource is{" "}
          <TextHighlight>not marked</TextHighlight> as downloaded.
        </Text>
        <TextImageBlock>
          <Image
            loading="lazy"
            width={1491}
            height={754}
            fullView={true}
            className={classes["img"]}
            src={require("../../assets/about/14-img-examples-resources4.jpg")}
            alt="Image examples resources 2"
            srcSet={require("../../assets/about/14-img-examples-resources4.webp")}
            type="image/webp"
          />
        </TextImageBlock>
      </TextContentBlock>
    </AboutContentWrap>
  );
};

export default AboutModelPage;
